# Generated by Django 6.0.2 on 2026-03-30 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('icon', models.TextField(verbose_name='Ikona (SVG yoki emoji)')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('processing', 'Jarayonda'), ('shipped', 'Yetkazilmoqda'), ('delivered', 'Yetkazib berildi'), ('cancelled', 'Bekor qilindi')], default='new', max_length=20, verbose_name='Holati')),
                ('payment_type', models.CharField(choices=[('cash', 'Naqd pul'), ('card', 'Plastik karta'), ('online', "Online to'lov")], default='cash', max_length=10, verbose_name="To'lov turi")),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Jami narx')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Buyurtma',
                'verbose_name_plural': 'Buyurtmalar',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Miqdori')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Narxi')),
            ],
            options={
                'verbose_name': 'Buyurtma mahsuloti',
                'verbose_name_plural': 'Buyurtma mahsulotlari',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Nomi')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True, verbose_name='Tavsifi')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Narxi (so'm)")),
                ('old_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Eski narxi')),
                ('stock', models.PositiveIntegerField(default=0, verbose_name='Omborda soni')),
                ('is_available', models.BooleanField(default=True, verbose_name='Mavjudmi')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200, verbose_name="To'liq ism")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon')),
                ('city', models.CharField(default='Toshkent', max_length=100, verbose_name='Shahar')),
                ('address', models.CharField(max_length=300, verbose_name='Manzil')),
                ('zip_code', models.CharField(blank=True, max_length=20, verbose_name='Pochta indeksi')),
                ('is_default', models.BooleanField(default=False, verbose_name='Asosiy manzil')),
            ],
            options={
                'verbose_name': 'Yetkazish manzili',
                'verbose_name_plural': 'Yetkazish manzillari',
            },
        ),
    ]
